name: student_id_scanner
description: A Flutter app for scanning student IDs using a Python backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  path: ^1.9.1
  camera: ^0.11.2+1
  provider: ^6.0.0
  excel: ^4.0.6
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  syncfusion_flutter_xlsio: ^29.2.11
  flutter_tesseract_ocr: any
  image: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/DITrix.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/image/DITrix.jpg
    - assets/tessdata/eng.traineddata