name: student_id_scanner
description: A Flutter app for scanning student IDs using a Python backend.
publish_to: 'none'
version: 1.1.2+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  image: any
  path: ^1.9.1
  excel: ^4.0.6
  camera: ^0.11.2+1
  provider: ^6.0.0
  url_launcher: ^6.3.2
  file_picker: ^10.3.3
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  flutter_tesseract_ocr: ^0.4.30
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  syncfusion_flutter_xlsio: ^29.2.11
  google_mlkit_text_recognition: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/DITrix.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/image/DITrix.jpg
    - assets/tessdata/eng.traineddata